### PR TITLE
Adds a definition to "unit test" in the tech dictionary

### PR DESCRIPTION
**Pull request by avinashi10**
## This PR fixes...

The missing "unit test" definition in the Tech Dictionary

## What I did...

- Added a definition to the dictionary entry "unit test"
- Added a source url for the definition

## How to test...

1. In your local repo, from the `pit` branch, fetch the latest changes with `git fetch` and `git pull` (First refer to https://github.com/cherryontech/website/blob/pit/README.md if you have not yet cloned the repo locally). 
2. Switch to the branch containing this change with `git switch unitTestDictionary` 
3. Run `npm install` or `yarn install`
4. Run `gridsome develop` to start a local dev server. In the terminal, you will see an address such as `http://localhost:8080/`. Navigate to that address in a browser.
5. Navigate to the Dictionary page and search for "unit test" or scroll down to the "unit test" entry (NOTE: this is a different entry than "Unit testing")
6. Ensure that you can see the definition of unit test and that the definition makes sense

## I learned...

I got to see a bit of how Gridsome and VueJS work!

### CODE REVIEW

**Review by YashsviG — APPROVED** [review]

**Review by shyusu4 — APPROVED** [review]
Hi Archaa, great job on this PR! I like how detailed your intructions are on how to test the changes!

**Comment by alliequintano** [comment]
Try removing the package-lock.json and yarn.lock files from your PR and we'll see if that resolves the build errors 👍

**Review by alliequintano — CHANGES_REQUESTED** [review]
We do not want to delete the existing lock file from the repo. Your PR should show no changes to the yarn.lock file / it should not be included in the PR. https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request

**Review by avinashi10 — COMMENTED** [review]
I reverted the branch back to its original state and then added the definition again- being sure to only stage the file with the definition

**Review by alliequintano — APPROVED** [review]
Nice job :D

**Pull request merged**
