### PR TITLE
added definition of callback hell

### PR DESCRIPTION
**Pull request by KatKowalik**
## This PR fixes...

This PR adds a definition for "callback hell" to the dictionary.

## What I did...

I added a definition for "callback hell" to the Dictionary. 

## How to test...

1. Navigate to https://cherryon.tech/dictionary/
2. Search the "callback hell" term.
3. Read the definition.

## I learned...
I learned that the alternative name for Callback Hell is the **Pyramid of Doom**, and I think I like this term better 😆

### CODE REVIEW

**Comment by alliequintano** [comment]
Hey! @khairahscorner pointed out to me that our build is failing for reasons unrelated to your PR. I am fixing that now and will update when it's working again! Sorry about that.

**Comment by alliequintano** [comment]
I am going to close and re-open your PR to retrigger the Netlify checks. A little weird but should work :D

**Comment by alliequintano** [comment]
>I am going to close and re-open your PR to retrigger the Netlify checks. A little weird but should work :D

Okay that didn't work, but I pushed an empty commit to retrigger the checks and now your Netlify preview is ready!!

**Comment by alliequintano** [comment]
Get job so far @KatKowalik! Can you please fill out the PR description with the template provided?

**Comment by KatKowalik** [comment]
@alliequintano Done! :)

**Review by TanyaPina — APPROVED** [review]
Looks good to me, thank you Kat!

**Review by alliequintano — CHANGES_REQUESTED** [review]
Good job Kat! Can you please update the definition to be full sentences? When reviewing the changes with the Netlify deploy preview, I see other definitions are written as complete sentences. Rather than starting with "is a term...", you could start with "A term used..", for example.

Please hit the button to request re-review from me after you've pushed your change!

**Comment by KatKowalik** [comment]
@alliequintano I changed the beginning to be a sentence, the rest I think looked fine, but let me know if you want me to change it.

**Review by alliequintano — APPROVED** [review]
Nice!

**Review by shelleymcq — APPROVED** [review]
This is a great add Kat!

suggestion: adding the alternate term you found would be nice. Just a simple (also known as 'Pyramid of Doom') at the end would do it.

**Comment by khairahscorner** [comment]
Merging this PR since all looks good! @shelleymcq your suggestion would be a great addition too!

**Pull request merged**
